package com.nutritareas.app.ui.theme

import androidx.compose.ui.graphics.Color

// Pastel pink + white palette (light - the app's primary look).
val PinkPrimaryLight = Color(0xFFE38AA4)
val OnPinkPrimaryLight = Color(0xFFFFFFFF)
val PinkPrimaryContainerLight = Color(0xFFFFD9E4)
val OnPinkPrimaryContainerLight = Color(0xFF5C2438)
val RoseSecondaryLight = Color(0xFFC97B93)
val OnRoseSecondaryLight = Color(0xFFFFFFFF)
val RoseSecondaryContainerLight = Color(0xFFF6D3DE)
val OnRoseSecondaryContainerLight = Color(0xFF5C2438)
val RoseTertiaryLight = Color(0xFFB96C86)
val OnRoseTertiaryLight = Color(0xFFFFFFFF)
val RoseTertiaryContainerLight = Color(0xFFF9DEE7)
val OnRoseTertiaryContainerLight = Color(0xFF4A1D2C)
val BackgroundLight = Color(0xFFFFF8FA)
val OnBackgroundLight = Color(0xFF4A3238)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF4A3238)
val SurfaceVariantLight = Color(0xFFFBE4EC)
val OnSurfaceVariantLight = Color(0xFF6E4A54)
val OutlineLight = Color(0xFFD9A8B6)

// Same family, deepened for dark mode so the brand still reads as "pink" at night.
val PinkPrimaryDark = Color(0xFFF0A8BE)
val OnPinkPrimaryDark = Color(0xFF4A1626)
val PinkPrimaryContainerDark = Color(0xFF6B3348)
val OnPinkPrimaryContainerDark = Color(0xFFFFD9E4)
val RoseSecondaryDark = Color(0xFFE3B8C6)
val OnRoseSecondaryDark = Color(0xFF3F212A)
val RoseSecondaryContainerDark = Color(0xFF5C3542)
val OnRoseSecondaryContainerDark = Color(0xFFF6D3DE)
val RoseTertiaryDark = Color(0xFFE0A0B5)
val OnRoseTertiaryDark = Color(0xFF40202B)
val RoseTertiaryContainerDark = Color(0xFF5C3542)
val OnRoseTertiaryContainerDark = Color(0xFFF9DEE7)
val BackgroundDark = Color(0xFF241419)
val OnBackgroundDark = Color(0xFFF3DDE3)
val SurfaceDark = Color(0xFF2B171D)
val OnSurfaceDark = Color(0xFFF3DDE3)
val SurfaceVariantDark = Color(0xFF4A2C36)
val OnSurfaceVariantDark = Color(0xFFD9BAC4)
val OutlineDark = Color(0xFF8C5A68)
